### PR TITLE
fix: omit Secure cookie attribute on plain-HTTP origins

### LINKED ISSUE #83: `wrangler dev` auth cannot persist because session cookies are always Secure
`npm run dev` now routes local development through `npx wrangler dev` (commit `6cce8e3846778dd6dbb946341f66393a683f4e8e`), but the worker still emits `Secure` session cookies unconditionally in [`src/worker/httpHandler.ts`](src/worker/httpHandler.ts):

- logout clears with `session=...; SameSite=Strict; Secure; Max-Age=0`
- auth verify sets `session=...; SameSite=Strict; Secure; Max-Age=86400`

Those cookie strings were introduced when the HTTP handler was split out in commit `5142505edeb0e5cdda8f51252446447b9e403367`.

On a plain-HTTP local dev origin, browsers will not store/send a `Secure` cookie, so wallet auth succeeds for the request that sets the cookie but the next `/api/me` or `/ws` request comes back unauthenticated. That makes the advertised local workflow unusable.

Minimal fix:
- Build the cookie attributes from `new URL(request.url).protocol`
- Only append `Secure` on HTTPS requests
- Reuse the same helper for both verify and logout so local clearing matches local setting

Nice-to-have regression test:
- Add a worker-route test that asserts the `Set-Cookie` header omits `Secure` for an `http://` request and includes it for `https://`.

### PR DESCRIPTION
**Pull request by 0xferit**
## Summary

- Adds a `cookieAttrs(request)` helper that inspects the request URL protocol and conditionally includes `; Secure` only for HTTPS origins
- Updates both the logout (`/api/logout`) and auth verify (`/api/auth/verify`) Set-Cookie headers to use this helper
- Fixes `wrangler dev` local auth: browsers were silently dropping `Secure` cookies on the plain-HTTP origin, making session persistence impossible
- Adds regression tests in `test/worker/http-routes.test.ts` asserting the `Secure` attribute is present for HTTPS and absent for HTTP on both `/api/auth/verify` and `/api/logout`

Closes #83

### CODE REVIEW

**Review by 0xferit — COMMENTED** [review]
The protocol-based `Secure` toggle looks correct for fixing local `wrangler dev` auth, but this PR should add the corresponding worker-route regression test before merging. There is already a `test/worker/http-routes.test.ts` harness in CI, and without an assertion for `http://` vs `https://` `Set-Cookie` behavior on the affected routes, this exact bug can regress silently.

File: src/worker/httpHandler.ts [hunk 1]
```diff
@@ -26,6 +26,11 @@ function errorResponse(message: string, status = 400): Response {
   return jsonResponse({ error: message }, status);
 }
 
+function cookieAttrs(request: Request): string {
```
Comment (0xferit) [inline src/worker/httpHandler.ts]: Please add a worker-route regression test for this branch. The repo already has `test/worker/http-routes.test.ts`, and this fix now depends on `request.url.protocol` staying correct: a future refactor back to a hard-coded `Secure` would break `wrangler dev` again without any failing test. I’d expect assertions that `/api/auth/verify` omits `Secure` on `http://...` and still includes it on `https://...`; `/api/logout` should be covered too since it reuses the same helper.

**Review by 0xferit — COMMENTED** [review]
The cookie-attribute change looks like the right fix for issue #83, but the PR still leaves the exact regression untested. This repo already has worker route tests, so I’d add focused coverage that proves `Secure` is omitted on plain-HTTP requests and still present on HTTPS requests. Without that, the local-dev auth breakage can come back on the next refactor with no failing test.
