### PR TITLE
fix: replay round_result on results-phase reconnect

### LINKED ISSUE #77: Results-phase reconnect never replays the round result
## Problem

The restore/reconnect flow added in commit `98706d21f8c5098f7d9bffa18eb94ad70f40ffe2` does not send enough state for a client that reconnects during the results phase.

## Evidence

`_sendMatchStateToPlayer()` in `src/worker.ts:1511-1565` handles `match.phase === 'results'` by sending:

- `round_start`
- `phase_change` with `phase: 'results'`
- `commit_status`
- `reveal_status`

It never sends the `round_result` payload that normal in-order clients receive from `_finalizeRound()`.

The frontend only renders results, updates balances, and enables chat inside `onRoundResult()` in `public/app.html:1033-1060`.

By contrast, `onPhaseChange()` in `public/app.html:994-1016` only handles `msg.phase === 'reveal'`; a replayed `phase_change` with `phase: 'results'` is ignored.

So a reconnecting player can land back in the match during results without:

- the result banner,
- updated balances from that round,
- results-phase chat being re-enabled.

## Why this matters

A player who reconnects after settlement but before the next round/game-over sees stale state right at the point where the UI is supposed to explain what just happened.

## Minimal fix

When replaying `match.phase === 'results'`, also send the latest `round_result` payload (or a dedicated reconnect-state message that includes the settled round outcome and balances).

If you want to keep the current protocol, the smallest safe change is:

1. cache the most recent round result on the match state after `_finalizeRound()`, and
2. emit that cached result from `_sendMatchStateToPlayer()` whenever `match.phase === 'results'`.

Then add a Worker reconnect test that restores a client during results and asserts the client receives a `round_result` message before the phase advances.

### PR DESCRIPTION
**Pull request by 0xferit**
## Summary

Fixes #77: clients reconnecting during the results phase now receive the `round_result` replay so they can render the results screen.

## Changes

- **Replay `round_result` on results-phase reconnect** (`src/worker.ts`): `_sendMatchStateToPlayer()` now sends the cached `lastRoundResult` payload when reconnecting during the `results` phase, so clients see the round outcome instead of a blank screen.
- **Checkpoint `lastRoundResult` for post-eviction restore** (`src/worker/persistence.ts`): added `last_round_result_json` column to `match_checkpoints`. The checkpoint/restore cycle now round-trips the result payload, covering DO eviction during the results window.
- **PRAGMA-based column migration** (`src/worker/persistence.ts`): uses `PRAGMA table_info` to check whether the `last_round_result_json` column exists before running `ALTER TABLE`, avoiding exceptions for normal control flow on every startup.
- **Fix test key count comment** (`test/worker/helpers.ts`): updated comment to reflect the actual 13 keys (indices 0-12).

### CODE REVIEW

File: src/worker.ts [hunk 1]
```diff
@@ -1417,6 +1431,7 @@ export class GameRoom {
         commitTimer: null,
         revealTimer: null,
         resultsTimer: null,
+        lastRoundResult: null,
```
Comment (0xferit) [inline src/worker.ts]: `_restoreMatchesFromStorage()` can bring back a match that is still in `phase === 'results'`, but this restores `lastRoundResult` as `null`. In that post-eviction reconnect path, `_sendMatchStateToPlayer()` still cannot replay `round_result`, so the client lands in the same blank results state described in `#77`. I think this payload needs to survive checkpoint/restore, or be reconstructed from persisted settlement data, for the fix to cover the restore/reconnect flow.

**Review by 0xferit — COMMENTED** [review]
1. The new replay cache is not restored from checkpoints, so a post-eviction reconnect during `results` still misses `round_result` and lands in the blank-results state from `#77`.
2. There is still no regression test for results-phase reconnect replay, so this path is unprotected in CI.

I would normally mark this `REQUEST_CHANGES`, but GitHub does not allow that on your own pull request from this account.

**Review by 0xferit — COMMENTED** [review]
Fresh review on the current head diff: the PRAGMA-based column check and explicit `ALTER TABLE` migration close the prior deploy-time schema risk, and I did not find a remaining correctness bug in the persistence or replay logic itself.

The remaining actionable gap is regression coverage. The new test exercises a warm reconnect during `results`, but this fix now depends on `last_round_result_json` being checkpointed and restored correctly after eviction. I would add a targeted restore-path regression test around the persisted `lastRoundResult` flow before merging so the new checkpoint/restore behavior is actually locked down.

GitHub does not allow this account to approve its own PR, so I’m recording this as a submitted comment review.
